from django.urls import (
    path,
    re_path,
    include,
)

from .views import (
    signup_view,
    login_view,
    logout_view,
    email_verification_sent_view,
    confirm_email_view,
    CustomLoginCancelledView,
    CustomLoginErrorView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetFromKeyView,
    CustomPasswordResetFromKeyDoneView,
    ProfileView,
    UpdateProfileView,
    email_view,
    password_change_view,
    password_change_done_view,
    password_set_view,
    password_set_done_view,
    CustomConnectionsView,
    SettingsView,
    DescriptionView,
    ProfileViewsList,
    NotificationView,
    NotificationDetailView,
    FindFriendView,
    InstructorWalletView,
    InstructorCoursesView,
    FollowView,
    FollowersAndFollowingView,
)

urlpatterns = [
    path(
        "followers/<int:pk>/",
        FollowersAndFollowingView.as_view(),
        name="followers-view",
    ),
    path("follow/<int:pk>/", FollowView.as_view(), name="follow-view"),
    path("my-course/", InstructorCoursesView.as_view(), name="instructor-courses"),
    path("wallet/<int:pk>/", InstructorWalletView.as_view(), name="wallet"),
    path("find-friends/", FindFriendView.as_view(), name="find-friends"),
    path(
        "notification-detail/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification-detail",
    ),
    path("notifications/", NotificationView.as_view(), name="notification"),
    path("profile-views/", ProfileViewsList.as_view(), name="profile-views"),
    path("my-description/", DescriptionView.as_view(), name="description"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path(
        "3rdparty/", CustomConnectionsView.as_view(), name="socialaccount_connections"
    ),
    path(
        "3rdparty/login/error/",
        CustomLoginErrorView.as_view(),
        name="socialaccount_login_error",
    ),
    path(
        "3rdparty/login/cancelled/",
        CustomLoginCancelledView.as_view(),
        name="socialaccount_login_cancelled",
    ),
    path(
        "password/change/done/",
        password_change_done_view,
        name="password_change_done",
    ),
    path(
        "password/change/",
        password_change_view,
        name="account_change_password",
    ),
    path(
        "password/set/done/",
        password_set_done_view,
        name="password_set_done",
    ),
    path("password/set/", password_set_view, name="account_set_password"),
    path("email/", email_view, name="account_email"),
    path("update-profile/", UpdateProfileView.as_view(), name="update-profile"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path(
        "password/reset/key/done/",
        CustomPasswordResetFromKeyDoneView.as_view(),
        name="account_reset_password_from_key_done",
    ),
    re_path(
        r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        CustomPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key",
    ),
    path(
        "password/reset/done/",
        CustomPasswordResetDoneView.as_view(),
        name="account_reset_password_done",
    ),
    path(
        "password/reset/",
        CustomPasswordResetView.as_view(),
        name="account_reset_password",
    ),
    path("login/", login_view, name="account_login"),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        confirm_email_view,
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        email_verification_sent_view,
        name="account_email_verification_sent",
    ),
    path("logout/", logout_view, name="account_logout"),
    path("signup/", signup_view, name="account_signup"),
    # Allauth Urls
    path("", include("allauth.urls")),
]
