# Generated by Django 6.0.5 on 2026-05-21 18:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=50, verbose_name='User Identifier')),
                ('topic', models.CharField(max_length=500, verbose_name='Topic')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Short Video Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Short Video Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Short Video Description')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Short Video File')),
                ('thumbnail', models.URLField(unique=True, verbose_name='Short Video Thumbnail Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_video', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Short Video',
                'verbose_name_plural': 'Short Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
