# Generated by Django 6.0.5 on 2026-05-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='report',
            name='topic',
            field=models.CharField(max_length=500, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_identifier',
            field=models.CharField(max_length=50, verbose_name='User Identifier'),
        ),
    ]
