# Generated by Django 6.0.5 on 2026-05-21 18:40

import cloudinary.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Course Slug')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube Link')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Github Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Course Thumbnail')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Course Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Course Instructor')),
                ('likes', models.ManyToManyField(blank=True, related_name='course_likes', to=settings.AUTH_USER_MODEL, verbose_name='Course Likes')),
                ('views', models.ManyToManyField(blank=True, related_name='course_views', to=settings.AUTH_USER_MODEL, verbose_name='Course Views')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Video Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video Description')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Video Duration')),
                ('formatted_duration', models.CharField(max_length=100, verbose_name='Formatted Video Duration')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Course Video File')),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Course Video Thumbnail Image')),
                ('thumbnail_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Course Video Thumbnail Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Video',
                'verbose_name_plural': 'Course Videos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollment', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled User')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='course.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Course Students'),
        ),
    ]
