# Generated by Django 6.0.5 on 2026-05-16 22:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Course Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('thumbnail', models.ImageField(upload_to='course/thumbnails/', verbose_name='Course Thumbnail')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Course Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Course Instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Video Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video Description')),
                ('video', models.FileField(upload_to='course/videos/', verbose_name='Video File')),
                ('thumbnail', models.ImageField(upload_to='course/video_thumbs/', verbose_name='Video Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Video',
                'verbose_name_plural': 'Course Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollment', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled User')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='course.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Course Students'),
        ),
        migrations.CreateModel(
            name='PublicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Video Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Video Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video Description')),
                ('video', models.FileField(upload_to='course/public_video/', verbose_name='Video File')),
                ('thumbnail', models.ImageField(upload_to='course/public_video/thumbnail/', verbose_name='Video Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_video', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Public Video',
                'verbose_name_plural': 'Public Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
