# Generated by Django 6.0.5 on 2026-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Course Description'),
        ),
    ]
