# Generated by Django 6.0.5 on 2026-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(blank=True, null=True, verbose_name='Course Description'),
        ),
    ]
