# Generated by Django 6.0.5 on 2026-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(blank=True, default={'0': '', '1': '', '10': '', '2': '', '3': '', '4': '', '5': '', '6': '', '7': '', '8': '', '9': ''}, null=True, verbose_name='Course Description'),
        ),
    ]
