# Generated by Django 6.0.5 on 2026-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
