# Generated by Django 6.0.5 on 2026-05-18 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='course_likes', to=settings.AUTH_USER_MODEL, verbose_name='Course Likes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='course_views', to=settings.AUTH_USER_MODEL, verbose_name='Course Views'),
        ),
    ]
