# Generated by Django 6.0.5 on 2026-05-24 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to=settings.AUTH_USER_MODEL, verbose_name='Views'),
        ),
    ]
