# Generated by Django 6.0.4 on 2026-05-05 23:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoractivation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
    ]
