# Generated by Django 6.0.4 on 2026-05-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instructoractivation_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorActivation',
        ),
    ]
